### PR TITLE
Shift to Typescript

### PR DESCRIPTION
**Pull request by ernman37**
## Updates

* Add shift client to typescript-react
* Did end up removing the `api.js` as we likely will redesign

### CODE REVIEW

**Comment by the-ernman** [comment]
- also added grommet

**Comment by danboberton** [comment]
This seems to break the run script, I'm going to try and get it working again from here

**Comment by the-ernman** [comment]
@danboberton Take a look now, I added it to where `npm start` script doesn't run in the background now we can see the errors and warnings live as it is compiling new react, let me know what you think.

 If you want to run it in the background I don't have an issue with that either. 

It still has some issues that could be worked out but overal runs docker and starts project 😂

**Comment by danboberton** [comment]
@ernman37 Rad, love it

**Pull request merged**
